version: "3.3"
services: 
    backend:
        build: ./backend/
        ports: 
            - "3333:3333"
        volumes: 
            - ./backend:/usr/src/app
    frontend:
        build: ./front-map/
        ports: 
            - "3000:3000"
        volumes: 
            - ./front-map:/usr/src/app
        depends_on: 
            - backend