version: '3'

services:
  backend:
    build: ./backend
    command: ["npm", "start"]
    ports:
        - 3333:3333
    volumes: 
        - ./backend:/usr/src/app/backend
  frontend:
    build: ./frontmap
    container_name: frontend
    volumes:
      - ./frontmap:/usr/src/app/front
      - ./frontmap/node-modules:/usr/src/app/front/
    ports:
      - "3000:80"
    depends_on: 
        - backend


